version: '2'

services:
  postgres:
    image: postgres:9.4
    environment:
      POSTGRES_USER: farm
      POSTGRES_PASSWORD: mypassword
    ports:
      - '5432:5432'
    volumes:
      - postgres:/var/lib/postgresql/data

  redis:
    image: redis:2.8
    ports:
      - '6379:6379'
    volumes:
      - redis:/var/lib/redis/data

  farm:
    build: .
    ports:
      - '8000:8000'
    volumes:
      - .:/farm
    env_file:
      - .farm.env

  sidekiq:
    build: .
    command: bundle exec sidekiq
    volumes:
      - .:/farm
    env_file:
      - .farm.env

volumes:
  redis:
  postgres:
